#!/usr/bin/env python3
"""Generate frozen clone page documents from the captured JEFIT source DOM.

For every anonymous checkpoint route the desktop ``page.html`` (rendered,
responsive, viewport-independent DOM) is rewritten so that every asset
reference resolves onto the vendored mirror under
``/static/assets/2026-08-18.jefit-r1/...`` and no remote URL survives into
shipped markup. Results land in ``clone/frontend/pages/<name>.html`` plus a
mechanical rewrite report.

Site policy (scope/implement-notes.md): the source is a client-rendered
Next.js SPA and the clone re-serves the *rendered* presentation, so every
``<script>`` block is dropped (SPA runtime, RSC payload, trackers alike) and
interaction is re-implemented clone-locally in ``/static/site/app.js``.

Mapping policy, purely mechanical:

1. Asset URLs (root-relative, first-party absolute, and captured third-party
   hosts) map onto the deterministic mirror location computed with the same
   ``local_relpath`` rule the capture harness used (query strings collapse to
   a sha256 ``.q<digest>`` suffix). If the payload exists on disk the
   reference is rewritten; content-host references whose payload was never
   fetched are still localized onto the deterministic path (they 404 locally
   instead of leaving the origin) and reported.
2. Mirrored stylesheets keep their byte-exact vendored copies; the documents
   reference *localized* CSS copies generated by build_localized_css.py under
   ``/static/css/...`` so url() references inside CSS resolve locally too.
3. Unmapped third-party link/img/iframe tags (trackers, widgets) are dropped;
   remaining third-party navigation hrefs become local ``/external/<slug>``
   boundary links.
"""
from __future__ import annotations

import hashlib
import html as html_lib
import json
import pathlib
import re
import urllib.parse

SITE = pathlib.Path(__file__).resolve().parents[1]
CAPTURE_ID = "2026-08-18.jefit-r1"
CAP_ROOT = SITE / "source-current" / CAPTURE_ID
PAGES_OUT = SITE / "clone" / "frontend" / "pages"
ASSET_ROOT = SITE / "clone" / "static" / "assets" / CAPTURE_ID
CSS_ROOT = SITE / "clone" / "static" / "css" / CAPTURE_ID
STATIC_PREFIX = f"/static/assets/{CAPTURE_ID}"
CSS_PREFIX = f"/static/css/{CAPTURE_ID}"
RUNTIME_TAG = '<script src="/static/site/app.js" defer></script>'

# checkpoint capture directory -> emitted page name (one per source route).
PAGES = {
    "home": "home",
    "elite": "elite",
    "exercises": "exercises",
    "exercises-page2": "exercises-page2",
    "exercise-detail": "exercise-detail",
    "routines": "routines",
    "routines-beginner": "routines-beginner",
    "routine-detail": "routine-detail",
    "build-routine": "build-routine",
    "login": "login",
    "forgot-password": "forgot-password",
    "signup": "signup",
    "signup-results": "signup-results",
    "signup-account-create": "signup-account-create",
    "support": "support",
    "support-faq": "support-faq",
    "about-us": "about-us",
    "ai-workout-tracker": "ai-workout-tracker",
    "adaptive-plan": "adaptive-plan",
    "use-case": "use-case",
    "watch": "watch",
    "coach": "coach",
    "our-story": "our-story",
    "community": "community",
    "blog": "blog",
    "terms-of-use": "terms-of-use",
    "privacy-policy": "privacy-policy",
    "ip-notice-process": "ip-notice-process",
    "press-media": "press-media",
    "not-found": "not-found",
}
# Extra captured states kept as build-time evidence pages (fixture extraction
# reads them; they are not served verbatim).
STATE_PAGES = {
    f"signup-step-{index:02d}": f"signup-step-{index:02d}"
    for index in range(1, 18)
}
STATE_PAGES.update(
    {
        "exercises-filter-abs": "exercises-filter-abs",
        "exercises-no-results": "exercises-no-results",
        "nav-products-dropdown": "nav-products-dropdown",
        "nav-workouts-dropdown": "nav-workouts-dropdown",
        "nav-more-dropdown": "nav-more-dropdown",
        "mobile-menu-open": "mobile-menu-open",
        "home-dark-mode": "home-dark-mode",
        "login-validation-empty": "login-validation-empty",
        "build-routine-validation-empty": "build-routine-validation-empty",
        "forgot-password-validation-empty": "forgot-password-validation-empty",
    }
)
EVIDENCE_OUT = SITE / "clone" / "frontend" / "evidence"

FIRST_PARTY_HOSTS = {"www.jefit.com", "jefit.com"}
# The site's own content hosts: references stay in the DOM localized onto the
# deterministic mirror path even when the payload was never fetched.
CONTENT_HOSTS = {"cdn.jefit.com", "cdn2.jefit.com", "cms.jefit.com"}
CAPTURED_HOSTS = {
    "www.jefit.com",
    "cdn.jefit.com",
    "cdn2.jefit.com",
    "fonts.googleapis.com",
    "fonts.gstatic.com",
    "stackpath.bootstrapcdn.com",
}

URL_ATTR = re.compile(
    r"""(?is)\b(href|src|srcset|imagesrcset|content|data-src|poster|action)"""
    r"""\s*=\s*(["'])(.*?)\2"""
)
SCRIPT_BLOCK = re.compile(r"(?is)<script\b[^>]*>.*?</script>")
LINK_TAG = re.compile(r"(?is)<link\b[^>]*/?>")
IFRAME_TAG = re.compile(r"(?is)<iframe\b[^>]*>\s*</iframe>")
IMG_TAG = re.compile(r"(?is)<img\b[^>]*/?>")
REMOTE_VALUE = re.compile(r"(?i)^(?:https?:)?//")
NAMESPACE_DECL = re.compile(r'(?i)\s+xmlns(?::[a-z0-9]+)?="https?://[^"]*"')
MICRODATA_IRI = re.compile(
    r'(?i)\s+(?:itemtype|vocab)="https?://(?:www\.)?schema\.org[^"]*"'
)


# Scope-owner asset-pipeline fix (2026-08-19): extension-less query-digest
# mirror files were renamed to carry their true extension. The map records
# old -> new runtime URLs; every computed mirror location goes through it.
_RENAMES_PATH = pathlib.Path(__file__).resolve().parent / "asset-renames.json"
RENAMED_RELS: dict[str, str] = {}
if _RENAMES_PATH.is_file():
    _prefix = f"{STATIC_PREFIX}/"
    for _old, _new in json.loads(_RENAMES_PATH.read_text()).items():
        RENAMED_RELS[_old.removeprefix(_prefix)] = _new.removeprefix(_prefix)


def mirror_rel(url: str) -> str:
    """Renamed mirror-relative location for one source URL."""

    rel = local_relpath(url)
    return RENAMED_RELS.get(rel, rel)


def local_relpath(url: str) -> str:
    """host/path mirror location; identical rule to tools/capture_assets.py."""

    parts = urllib.parse.urlsplit(url)
    path = parts.path.lstrip("/") or "index"
    if path.endswith("/"):
        path += "index"
    if parts.query:
        digest = hashlib.sha256(parts.query.encode()).hexdigest()[:10]
        stem, dot, suffix = path.rpartition(".")
        path = f"{stem}.q{digest}.{suffix}" if dot else f"{path}.q{digest}"
    segments = []
    for segment in path.split("/"):
        if len(segment.encode()) > 140:
            stem, dot, suffix = segment.rpartition(".")
            digest = hashlib.sha256(segment.encode()).hexdigest()[:16]
            segment = (
                f"h{digest}.{suffix}" if dot and len(suffix) <= 8 else f"h{digest}"
            )
        segments.append(segment)
    return f"{parts.netloc}/{'/'.join(segments)}"


def _absolute(url: str) -> urllib.parse.SplitResult | None:
    value = html_lib.unescape(url.strip())
    if not value or value.startswith(("data:", "blob:", "about:", "#", "mailto:")):
        return None
    if value.startswith("//"):
        value = "https:" + value
    if value.startswith("/"):
        value = "https://www.jefit.com" + value
    if not value.startswith(("http://", "https://")):
        return None
    return urllib.parse.urlsplit(value)


class Mapper:
    def __init__(self, report: dict) -> None:
        self.report = report
        css_names = set()
        manifest = json.loads(
            (SITE / "source-assets" / "manifest.json").read_text()
        )
        for asset in manifest["assets"]:
            if asset.get("mime_type") == "text/css":
                rel = asset["runtime_path"].split(f"assets/{CAPTURE_ID}/", 1)[1]
                css_names.add(rel)
        self.css_rels = css_names

    def map_asset(self, url: str) -> str | None:
        parts = _absolute(url)
        if parts is None:
            return None
        host = parts.netloc.casefold()
        if host not in CAPTURED_HOSTS | CONTENT_HOSTS:
            return None
        rel = mirror_rel(
            urllib.parse.urlunsplit(("https", host, parts.path, parts.query, ""))
        )
        if rel in self.css_rels:
            return f"{CSS_PREFIX}/{rel}"
        if (ASSET_ROOT / rel).is_file():
            return f"{STATIC_PREFIX}/{rel}"
        if parts.path == "/_next/image" and parts.query:
            # Uncaptured optimizer variant whose ORIGINAL image is mirrored
            # (e.g. the exercise-rail originals): serve the original.
            source = urllib.parse.parse_qs(parts.query).get("url", [""])[0]
            if source:
                if source.startswith("/"):
                    source = f"https://www.jefit.com{source}"
                original_rel = mirror_rel(source)
                if (ASSET_ROOT / original_rel).is_file():
                    return f"{STATIC_PREFIX}/{original_rel}"
        if host in FIRST_PARTY_HOSTS and parts.path.startswith("/_next/"):
            # Uncaptured Next.js optimizer variant (a 2x/lazy width the
            # capture viewport never fetched): deterministic mirror path,
            # local 404 rather than an unresolvable route.
            self.report["content_fallback_refs"].append(
                html_lib.unescape(url.strip())[:120]
            )
            return f"{STATIC_PREFIX}/{rel}"
        if host in CONTENT_HOSTS:
            self.report["content_fallback_refs"].append(
                html_lib.unescape(url.strip())[:120]
            )
            return f"{STATIC_PREFIX}/{rel}"
        return None


def rewrite_document(html: str, mapper: Mapper, report: dict) -> str:
    def drop_script(match: re.Match) -> str:
        open_tag = match.group(0)[: match.group(0).find(">") + 1]
        if re.search(r'(?i)type\s*=\s*["\']application/ld\+json["\']', open_tag):
            report["ld_json_dropped"] += 1
        report["script_blocks_dropped"] += 1
        return ""

    def drop_or_keep(match: re.Match, kind: str) -> str:
        tag = match.group(0)
        if kind == "link":
            if re.search(
                r'(?i)\brel\s*=\s*["\'](?:preconnect|dns-prefetch)["\']', tag
            ) and re.search(r"""(?is)\bhref\s*=\s*["'](?:https?:)?//""", tag):
                report["dropped_tags"].append("link:network-hint")
                return ""
            if re.search(r'(?i)\bas\s*=\s*["\']script["\']', tag) or re.search(
                r'(?i)\brel\s*=\s*["\']modulepreload["\']', tag
            ):
                report["dropped_tags"].append("link:script-preload")
                return ""
        url_match = re.search(r"""(?is)(?:src|href)\s*=\s*["']([^"']+)["']""", tag)
        if not url_match:
            return tag
        url = url_match.group(1)
        if not REMOTE_VALUE.match(url.strip()):
            return tag
        parts = _absolute(url)
        host = parts.netloc.casefold() if parts else ""
        if (
            mapper.map_asset(url) is not None
            or host in FIRST_PARTY_HOSTS
            or host in CONTENT_HOSTS
        ):
            return tag
        report["dropped_tags"].append(f"{kind}:{url[:100]}")
        return ""

    html = SCRIPT_BLOCK.sub(drop_script, html)
    html = LINK_TAG.sub(lambda m: drop_or_keep(m, "link"), html)
    html = IFRAME_TAG.sub(lambda m: drop_or_keep(m, "iframe"), html)
    html = IMG_TAG.sub(lambda m: drop_or_keep(m, "img"), html)
    html = NAMESPACE_DECL.sub("", html)
    html = MICRODATA_IRI.sub("", html)

    def replace_attr(match: re.Match) -> str:
        attr, quote, value = match.group(1), match.group(2), match.group(3)
        if attr.casefold() in ("srcset", "imagesrcset"):
            chunks = []
            changed = False
            for chunk in value.split(","):
                chunk = chunk.strip()
                if not chunk:
                    continue
                pieces = chunk.split()
                mapped = mapper.map_asset(pieces[0])
                if mapped:
                    pieces[0] = mapped
                    changed = True
                chunks.append(" ".join(pieces))
            if changed:
                report["rewritten"] += 1
                return f'{attr}={quote}{", ".join(chunks)}{quote}'
            return match.group(0)
        mapped = mapper.map_asset(value)
        if mapped:
            report["rewritten"] += 1
            return f"{attr}={quote}{mapped}{quote}"
        return match.group(0)

    html = URL_ATTR.sub(replace_attr, html)

    def replace_css_url(match: re.Match) -> str:
        target = match.group(1).strip("'\"")
        mapped = mapper.map_asset(target)
        if mapped is None and REMOTE_VALUE.match(target):
            # Third-party CSS background (an injected widget stylesheet):
            # localize onto the deterministic mirror path — a local 404,
            # never a remote request.
            parts = _absolute(target)
            if parts is not None:
                mapped = f"{STATIC_PREFIX}/{mirror_rel(parts.geturl())}"
                report["content_fallback_refs"].append(target[:120])
        if mapped:
            report["rewritten"] += 1
            return f"url({mapped})"
        return match.group(0)

    def rewrite_css_scope(scope_match: re.Match) -> str:
        return re.sub(
            r"url\(\s*([^)]+?)\s*\)", replace_css_url, scope_match.group(0)
        )

    # CSS url() references are rewritten ONLY inside style attributes and
    # <style> blocks. Tailwind arbitrary-value class tokens
    # (class="bg-[url('/x.jpg')]") must stay byte-identical to their escaped
    # stylesheet selectors, so class attributes are never touched — the
    # matching stylesheet declaration is localized by build_localized_css.
    html = re.sub(r"(?is)<style\b[^>]*>.*?</style>", rewrite_css_scope, html)
    html = re.sub(
        r"""(?is)\bstyle\s*=\s*"[^"]*"|\bstyle\s*=\s*'[^']*'""",
        rewrite_css_scope,
        html,
    )

    # First-party absolute URLs (canonical, og:url, nav links) become local
    # paths on the clone origin.
    def strip_origin(match: re.Match) -> str:
        report["first_party_localized"] += 1
        return "/" + match.group(1).lstrip("/")

    html = re.sub(
        r"(?i)https?://(?:www\.)?jefit\.com/?([^\"'\s<>)\\]*)", strip_origin, html
    )
    html = re.sub(
        r"(?i)(?<![:\w/])//(?:www\.)?jefit\.com/?([^\"'\s<>)\\]*)",
        strip_origin,
        html,
    )

    # Remaining third-party navigation targets keep their visible affordance
    # but point at the local external-boundary route.
    def boundary(match: re.Match) -> str:
        url = match.group(3)
        parts = urllib.parse.urlsplit(html_lib.unescape(url), scheme="https")
        slug = re.sub(r"[^a-z0-9.-]+", "-", parts.netloc.casefold()) or "external"
        report["external_boundaries"].append(url[:90])
        return f"{match.group(1)}={match.group(2)}/external/{slug}{match.group(2)}"

    html = re.sub(
        r"""(?is)\b(href)\s*=\s*(["'])(https?://[^"']+|//[^"']+)\2""",
        boundary,
        html,
    )
    if RUNTIME_TAG not in html:
        html = html.replace("</body>", f"{RUNTIME_TAG}</body>", 1)
    return html


def static_refs(html: str) -> set[str]:
    refs = set(re.findall(r"/static/[^\s\"'<>),]+", html))
    return {urllib.parse.urldefrag(r.split("?", 1)[0])[0] for r in refs}


def remaining_remote(html: str) -> list[str]:
    """Runtime-loadable remote references, matching the diagnostics audit
    (src/href/action attributes and CSS url() — plain-text URLs inside page
    copy and DOCTYPE/profile metadata are never fetched)."""

    return sorted(
        set(
            re.findall(
                r"(?i)(?:src|href|action|url)\s*[=(:]\s*[\"']?\s*"
                r"(?:https?:)?//(?!localhost|127\.0\.0\.1)[a-z0-9.-]+\.[a-z]{2,}"
                r"[^\"'\s<>)\\]*",
                html,
            )
        )
    )


# Static visual-parity stand-in for the Google GSI button. The source login
# renders it inside an accounts.google.com iframe, which the rewriter drops
# (never a live provider frame); this button reproduces the captured
# appearance and the clone runtime answers clicks with the honest
# clone-local notice, exactly like the Apple/Facebook buttons.
GSI_BUTTON = (
    '<button type="button" aria-label="Sign in with Google" '
    'data-clone-idp="google" style="width:320px;height:40px;display:flex;'
    "align-items:center;justify-content:center;gap:10px;background:#fff;"
    "border:1px solid #dadce0;border-radius:8px;font:500 15px/1 "
    "-apple-system,'Segoe UI',Roboto,Arial,sans-serif;color:#3c4043;"
    'cursor:pointer">'
    '<svg width="18" height="18" viewBox="0 0 48 48" aria-hidden="true">'
    '<path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 '
    '2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 '
    '17.74 9.5 24 9.5z"/>'
    '<path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h'
    '12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 '
    '7.09-17.65z"/>'
    '<path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-'
    '3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 '
    '10.78l7.97-6.19z"/>'
    '<path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c'
    '-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 '
    '6.19C6.51 42.62 14.62 48 24 48z"/>'
    "</svg><span>Sign in with Google</span></button>"
)
_GSI_SLOT = '<div class="S9gUrf-YoZ4jf" style="position: relative;"><div></div></div>'


def bake_forms(name: str, doc: str) -> str:
    """Bake real local form posts into the auth documents on disk (the
    captured SPA forms have no action; the derive gate and the clone's own
    handlers need literal <form method=post action=...> markup)."""

    if name == "login":
        doc = doc.replace(
            '<form class="space-y-4">',
            '<form class="space-y-4" method="post" action="/login">',
            1,
        )
        inputs = list(re.finditer(r"<input ", doc))
        for match, extra in zip(inputs[:2],
                                ('name="username" ', 'name="password" ')):
            at = match.end()
            doc = doc[:at] + extra + doc[at:]
            inputs = list(re.finditer(r"<input ", doc))
        if _GSI_SLOT in doc:
            doc = doc.replace(
                _GSI_SLOT,
                '<div class="S9gUrf-YoZ4jf" style="position: relative;">'
                + GSI_BUTTON
                + "</div>",
                1,
            )
    elif name == "forgot-password":
        # the captured legacy endpoint is localized onto the clone handler
        doc = re.sub(
            r'action="/forum_mod_backup/[^"]*"',
            'action="/login/forgot-password"',
            doc,
            count=1,
        )
        if 'name="email"' not in doc:
            doc = doc.replace('<input type="email" ',
                              '<input type="email" name="email" ', 1)
    elif name == "signup-account-create":
        doc = re.sub(
            r"<form(?![^>]*action=)",
            '<form method="post" action="/signup/register"',
            doc,
            count=1,
        )
        if 'name="email"' not in doc:
            doc = doc.replace('<input id="email" ',
                              '<input id="email" name="email" ', 1)
    return doc


def build(pages: dict[str, str], out_dir: pathlib.Path, summary: dict) -> set[str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    missing: set[str] = set()
    for checkpoint, name in pages.items():
        source = CAP_ROOT / checkpoint / "desktop" / "page.html"
        if not source.is_file():
            summary[name] = {"error": "missing capture"}
            continue
        report = {
            "rewritten": 0,
            "dropped_tags": [],
            "content_fallback_refs": [],
            "script_blocks_dropped": 0,
            "ld_json_dropped": 0,
            "first_party_localized": 0,
            "external_boundaries": [],
        }
        mapper = Mapper(report)
        rewritten = rewrite_document(source.read_text(), mapper, report)
        rewritten = bake_forms(name, rewritten)
        out_path = out_dir / f"{name}.html"
        out_path.write_text(rewritten)
        page_missing = sorted(
            ref
            for ref in static_refs(rewritten)
            if not (SITE / "clone" / ref.lstrip("/")).exists()
        )
        missing.update(page_missing)
        remote = remaining_remote(rewritten)
        summary[name] = {
            "bytes": out_path.stat().st_size,
            "rewritten_refs": report["rewritten"],
            "script_blocks_dropped": report["script_blocks_dropped"],
            "ld_json_dropped": report["ld_json_dropped"],
            "dropped_tags": sorted(set(report["dropped_tags"])),
            "content_fallback_refs": sorted(set(report["content_fallback_refs"])),
            "first_party_localized": report["first_party_localized"],
            "external_boundaries": sorted(set(report["external_boundaries"])),
            "missing_static_paths": page_missing,
            "remaining_remote_refs": remote[:40],
            "remaining_remote_count": len(remote),
        }
        print(
            f"  {name}: rewrote {report['rewritten']}, scripts-dropped "
            f"{report['script_blocks_dropped']}, missing {len(page_missing)}, "
            f"remote-left {len(remote)}"
        )
    return missing


def main() -> int:
    summary: dict = {}
    missing = build(PAGES, PAGES_OUT, summary)
    state_summary: dict = {}
    missing |= build(STATE_PAGES, EVIDENCE_OUT, state_summary)
    summary["_states"] = state_summary
    remote_total = sum(
        v.get("remaining_remote_count", 0)
        for section in (summary, state_summary)
        for v in section.values()
        if isinstance(v, dict)
    )
    summary["_totals"] = {
        "pages": len(PAGES),
        "state_pages": len(STATE_PAGES),
        "remaining_remote_total": remote_total,
        "missing_static_paths_union": sorted(missing),
    }
    (SITE / "clone" / "frontend" / "rewrite-report.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n"
    )
    return 0 if remote_total == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
