name: diagnostics (ipvanish)
on:
  pull_request:
    paths:
      - materials/ipvanish/**
      - .github/workflows/tests-ipvanish.yml
      - .github/workflows/clone-diagnostics.yml
  push:
    paths:
      - materials/ipvanish/**
      - .github/workflows/tests-ipvanish.yml
      - .github/workflows/clone-diagnostics.yml
permissions:
  contents: read
concurrency:
  group: diagnostics-ipvanish-${{ github.ref }}
  cancel-in-progress: true
jobs:
  diagnostics:
    uses: ./.github/workflows/clone-diagnostics.yml
    with:
      site: ipvanish
